name: Daily updater

on:
  #workflow_dispatch
  schedule:
    - cron:  '10 03 * * *'

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT_PARAMS update && $APT_PARAMS install colordiff -y
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/python-scripts-requirements.txt

    - name: Grabbing latest versions
      run: |
        cd $GITHUB_WORKSPACE
        
        find . -iname "*-scraper.py" -print0 | while read -d $'\0' entry
        do
          CWD=$(pwd)
          SCRAPEDIR=$(dirname "$entry")
          SCRAPESCRIPT=$(basename "$entry")
          cd "$SCRAPEDIR"
          
          echo "$SCRAPESCRIPT"
          python3 -Wall $SCRAPESCRIPT
          echo "----------------"
          cd "$CWD"
        done
        
    - name: Checking new versions
      run: |
        cd $GITHUB_WORKSPACE
        
        find . -maxdepth 2 -iname "*.csv"  -print0 | while read -d $'\0' entry
        do
          CSVDIR=$(dirname "$entry")
          CSVGIT=$(basename "$entry")
         
          echo "[+] $entry"
          colordiff -s "$entry" "$CSVDIR/_source/$CSVGIT" || true
          mv -f "$CSVDIR/_source/$CSVGIT" "$entry"
          echo "----------------"
        done
        
        git config user.name updating-bot
        git config user.email github-actions@github.com
        git pull
        git commit -a -m "updating bot - $(date --date="yesterday" '+%Y/%m/%d')"
        git push
